### ISSUE TITLE
Allow user to mark boards as 'favourites'

### ISSUE THREAD

**Issue by kasztof** [kasztof/taskManager#10]
User should be able to mark his boards as favoutires. Favourites boards should appear at the top of user boards list.

**Comment by Marlysson** [comment]
Based on statement : "Appear at the top of user boards list" 
The boards appears in a list to top-down listing ?

And not horizontally like trello..

**Comment by kasztof** [comment]
They can appear horizontally, and if so, the favourites boards should be on the left
