### ISSUE TITLE
Make separate .js file with scripts

### ISSUE THREAD

**Issue by kasztof** [kasztof/taskManager#25]

**Comment by Marlysson** [comment]
What help do you need?

**Comment by kasztof** [comment]
I was trying to include js file like that: <script src="{% static 'script.js' %}"></script>  but it doesnt work. I was trying to add {% load staticfiles %} setting STATICFILES_DIRS but still cant get it to work.

**Comment by Marlysson** [comment]
Do you put this file in a folder?

**Comment by kasztof** [comment]
yup static/js/script.js

**Comment by Marlysson** [comment]
Then you should use '{% static 'js/script.js' %}'

**Comment by Marlysson** [comment]
You did man?

**Comment by kasztof** [comment]
Yup its done, but it worked after I created {% block script %} for including .js files in templates which are extending base.html
